apiDebug: false
password: '1234'
timeout: 600000
libPath: ./server/lib
contractsPath: ./contracts/

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    explorerUrl: 'http://p2p-n0.eastus.cloudapp.azure.com:9000'
    stratoUrl: 'http://p2p-n0.eastus.cloudapp.azure.com/strato-api'
    blocUrl: 'http://p2p-n0.eastus.cloudapp.azure.com/bloc/v2.2'
    searchUrl: 'http://p2p-n0.eastus.cloudapp.azure.com/cirrus'
  - id: 1
    explorerUrl: 'http://p2p-n1.eastus.cloudapp.azure.com:9000'
    stratoUrl: 'http://p2p-n1.eastus.cloudapp.azure.com/strato-api'
    blocUrl: 'http://p2p-n1.eastus.cloudapp.azure.com/bloc/v2.2'
    searchUrl: 'http://p2p-n1.eastus.cloudapp.azure.com/cirrus'
  - id: 2
    explorerUrl: 'http://p2p-n2.eastus.cloudapp.azure.com:9000'
    stratoUrl: 'http://p2p-n2.eastus.cloudapp.azure.com/strato-api'
    blocUrl: 'http://p2p-n2.eastus.cloudapp.azure.com/bloc/v2.2'
    searchUrl: 'http://p2p-n2.eastus.cloudapp.azure.com/cirrus'
